[package]
name = "slipway_givenergy_cloud"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = "0.4.40"
serde = { version = "1.0.219", features = ["serde_derive"] }
serde_json = "1.0.140"
wit-bindgen = "0.41.0"
